spring:
  datasource:
    url: jdbc:mysql://localhost:(port)/blog_db?serverTimezone=UTC
    username: username
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    enabled: true
    #cache: false

